services:
  testDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs: /var/lib/postgresql
    ports:
      - 5432:5432

  backend:
    environment:
      - DB_HOST=testDB
    build: backend
    depends_on:
      testDB:
        condition: service_healthy
    ports:
      - 4001:4001
    volumes:
      - ./backend/src:/app/src
    healthcheck:
      test: 'curl --fail --request GET -H ''content-type:application/json'' --url ''http://localhost:4001/graphql?query=%7B__typename%7D'''
      interval: 5s
      timeout: 5s
      retries: 10
    

  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    healthcheck:
      test: "curl --fail --request GET --url http://localhost:3000"
      interval: 5s
      timeout: 5s
      retries: 30

  testrunner:
    build: 
      dockerfile: e2e-tests/Dockerfile
      context: ./
    environment:
      DB_HOST: testDB
      BASE_URL: http://localhost:3000
    volumes:
      - ./backend/src/:/backend/src/
      - ./e2e-tests/playwright-report:/e2e-tests/playwright-report
      - ./e2e-tests/test-results:/e2e-tests/test-results
      - ./e2e-tests/src:/e2e-tests/src
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
