name: e2e-tests

on:
  pull_request:
  workflow_call:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: cd e2e-tests && npm ci
      - name: Install Playwright Browsers
        run: cd e2e-tests && npx playwright install --with-deps
      - name: Start app
        run: cd e2e-tests && npx playwright test
      - name: Run Playwright tests
        run: cd e2e-tests && npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-tests/playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30
