name: integration-tests

on:
  pull_request:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Make envfile
        run: |
          echo JWT_PRIVATE_KEY=zeyfgzeigfyzegfyuzegf >> ./backend/.env
          echo NODE_ENV=test >> ./backend/.env
          echo CORS_ALLOWED_ORIGINS=http://localhost:3000 >> ./backend/.env
          echo SERVER_HOST=localhost >> ./backend/.env
          echo SERVER_PORT=4000 >> ./backend/.env
          echo DB_HOST=testDB >> ./backend/.env
          echo DB_PORT=5432 >> ./backend/.env
          echo DB_USER=postgres >> ./backend/.env
          echo DB_PASS=postgres >> ./backend/.env
          echo DB_NAME=postgres >> ./backend/.env

      - name: "Install npm and deps"
        run: cd backend && npm i
      - name: Run tests
        run: npm run integration-tests
